### ISSUE TITLE
CPU load in receive_data()

### ISSUE THREAD

**Issue by picatextra** [X-CASH-official/xcash-dpops#15]
With the use of parameter MSG_DONTWAIT for recvfrom , the thread will loop in receive_data() function until RECEIVE_DATA_SOCKET_TIMEOUT

a comment says: 

> use MSG_DONTWAIT so we dont block the program if there is no data 

but the code is not efficient

i recommand to safe some CPU and actually don't block 
1/ use the timeout which is already set (by removing MSG_DONTWAIT )
2/ or exit the loop if recvfrom returns an error (-1)

**Comment by zachhildreth** [comment]
Hi @picatextra 
For for first solution this will not work becuase if this flag is not set or the socket is blocking, then any time it encounters a timeout it will use the OS default timeout of over 1 minute in my test, since there is no way to set a timeout to these functions, unless were using the [setsockopt](http://man7.org/linux/man-pages/man3/setsockopt.3p.html) with SO_RCVTIMEO or SO_SNDTIMEO referenced at http://man7.org/linux/man-pages/man7/socket.7.html

However the second option makes sense. I prefer to not use a delay if the socket is waiting since this will increase the latency due to the delay and any context switching by the CPU, however it does not make sense like you mentioned to loop for the timeout time, if the error is not telling us to try again and is actually giving an error.

We can check [errno](http://man7.org/linux/man-pages/man3/errno.3.html) for non blocking sockets referenced http://man7.org/linux/man-pages/man7/socket.7.html and for [recv](http://man7.org/linux/man-pages/man2/recv.2.html) using the MSG_DONTWAIT but just check if there is an error and its errno is not EAGAIN or EWOULDBLOCK then exit the loop.

I noticed by changing these it fixed a potential loss of not sending data in the **block_verifiers_send_data_socket** function and fixed an error with non blocking sockets for the HTTP server in **send_data_socket** function as well

changes have been made in commit 257e7d3a50f86804f0461b31f6322e2c1ca845f3

Since this is not really a bug, but did lead to a few improvements and a potential bug we can do a bug bounty for this one

### CVSS Score
### We have determined that the [CVSS score for this bug](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N/CR:L/IR:L/AR:L/MAV:L/MAC:L/MPR:N/MUI:N/MS:U/MC:N/MI:N/MA:N&version=3.1) is a 0

So according to the [Bug Bounty official documentation](https://docs.xcash.foundation/contribute/bug-bounty-program) this bug qualifies for a award between $5.00 and 25.00 USD

## The team has decided that the final awarded amount will be $10.00 USD

### Please post a X-CASH Wallet address in the comments, and we will send the payment in a public transaction, post the transaction hash and then close the issue.

Thank you for helping out the DPOPS by finding this bug.

**Comment by picatextra** [comment]
Thank you for the fix, it looks good

**Comment by picatextra** [comment]
XCA1ka4bXH1bnvdT8vti1S12PfyH8fJ5XDUXyNRusyMRTBfFCawywJyCV5vvG38h71GAv77WotbmwbmbJen5bQpC7GeVx8gSws

**Comment by picatextra** [comment]
@plbgnt 👀

**Comment by plbgnt** [comment]
### Bounty Paid ✅ 

**Date:** 2020-08-04
**Amount (USD):** $10
**Amount (XCASH):** 643086.82 XCASH
**Spot Price:** 0.00001555 USD/XCASH
**XCASH Address:** XCA1ka4bXH1bnvdT8vti1S12PfyH8fJ5XDUXyNRusyMRTBfFCawywJyCV5vvG38h71GAv77WotbmwbmbJen5bQpC7GeVx8gSws 
**Tx Hash:** 93bc1e5d7dfcd3afdb53db339e8a0f537cccc9db214981c1ab21f4aa463b4623 
**Link:** https://explorer.x-cash.org/Transaction?data=93bc1e5d7dfcd3afdb53db339e8a0f537cccc9db214981c1ab21f4aa463b4623"
